### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by harlows** [infolit-idaho/infolit-for-everyone#3]
Just noticed [the link to your ALA presentation](https://www.ala.org/acrl/sites/ala.org.acrl/files/content/conferences/confsandpreconfs/2021/StudentAchievementUnlocked.pdf) on the [Don't stress, SIFT](https://github.com/infolit-idaho/infolit-for-everyone/blob/main/_content-pages/01-sift-moves.md) page is broken. It's available [via the Internet Archive](https://web.archive.org/web/20230305001249/https://www.ala.org/acrl/sites/ala.org.acrl/files/content/conferences/confsandpreconfs/2021/StudentAchievementUnlocked.pdf), although you might have a better source.

**Comment by ryan-p-randall** [comment]
Thank you so much for letting us know!  

I've deposited a [copy at Humanities Commons](https://hcommons.org/deposits/item/hc:65955/) (which is soon to [rebrand as "Knowledge Commons"](https://team.hcommons.org/2024/05/01/a-commons-by-any-other-name/), by the way) and replaced the link.
